# Generated by Django 5.0.3 on 2024-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdetail',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdetail',
            name='from_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdetail',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdetail',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfdetail',
            name='to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdetail',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
