# Generated by Django 5.0.3 on 2024-03-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0002_pdfdetail_due_date_pdfdetail_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('client_pancard', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_words', models.CharField(max_length=200)),
            ],
        ),
    ]
